### ISSUE TITLE
Add namespace support

### ISSUE THREAD

**Issue by rjmooney** [Agrimatics/activemodel-datastore#13]
Cloud Datastore supports multi-tenancy through entity namespaces. This allows for logical separation of content: in our case, customer content. Currently, entities created using Active Model Datastore are created in the default namespace exclusively.

See the following for more information:

**Multitenancy**
https://cloud.google.com/datastore/docs/concepts/multitenancy

**Entities, Properties, and Keys**
https://cloud.google.com/datastore/docs/concepts/entities

**Comment by bmclean** [comment]
I’m closing this issue because it has been inactive for a year. It seems no one has the time to implement this.

Please reopen if this feature is still needed and you have the time to see it through.

Thank you!
