### ISSUE TITLE
Easier testing: the emulator can run in a docker container

### ISSUE THREAD

**Issue by rud** [Agrimatics/activemodel-datastore#17]
Google even provides it: https://hub.docker.com/r/google/cloud-sdk/

Would that be something that was interesting to setup? Running tests on CI would be fairly easy using that.

**Comment by bmclean** [comment]
Hi @rud. Thanks for reaching out! Yes, running tests on CI is something we are interested in.

**Comment by rud** [comment]
All done in #18, a maintainer just has to enable Travis CI on this repo :)
