### ISSUE TITLE
validating uniqueness

### ISSUE THREAD

**Issue by sam0x17** [Agrimatics/activemodel-datastore#22]
I was wondering if there is a built in way to do this, and/or what the best/proper way would be. Would love it if there was syntax like:

```ruby
validates :email, uniqueness: true
```

**Comment by bmclean** [comment]
Hi @sam0x17! Thanks for reaching out. There isn't a built in uniqueness validation within active model-datastore. However, it can be implemented through Active Model.

Something like this:

```
class User
  include ActiveModel::Datastore

  attr_accessor :email

  validate :email_is_unique

  def entity_properties
    %w[email]
  end

  private

  def email_is_unique
    return unless email.present? && User.all(where: ['email', '=', email]).present?
    errors.add(:email, 'has already been used')
  end
end
```

Modify the actual lookup query (`User.all`) as needed (if you use ancestors, namespaces, etc). For a complete solution you probably want to look at using [track changes](https://github.com/Agrimatics/activemodel-datastore/blob/master/lib/active_model/datastore/track_changes.rb) as well. So you might add something like this:

`enable_change_tracking :email`

and modify the validator return to something like this:

`return unless email.present? && email_changed? && User.all(where: ['email', '=', email]).present?`

**Comment by bmclean** [comment]
@sam0x17 Did this work for you?
