### ISSUE TITLE
set entity name

### ISSUE THREAD

**Issue by MiguelSavignano** [Agrimatics/activemodel-datastore#30]
I would like to be able to change the entity name in datastore
similar to [table_name](https://apidock.com/rails/ActiveRecord/ModelSchema/ClassMethods/table_name) in active record.

**Comment by dan-appiphany** [comment]
As I see, we can set the entity name in datastore by using class method `name` in the model.
Example: 
`class User
   def self.name
       "Members"
   end
end`

**Comment by bmclean** [comment]
@MiguelSavignano Would the concept provided by @dan-appiphany work for you?
