### ISSUE TITLE
Using embedded entities

### ISSUE THREAD

**Issue by NielsKSchjoedt** [Agrimatics/activemodel-datastore#35]
I can't seem to figure out if it's supported to use [embedded entities](https://cloud.google.com/datastore/docs/concepts/entities#embedded_entity)? In case it is, how would the DSL for assigning such a property on a record look like in an example?

**Comment by bmclean** [comment]
Hi @NielsKSchjoedt!

Yes, we use embedded entities all the time. Let's say you have something like:
`attr_accessor :items            # Array`
defined on your primary model.

Then just call `build_entity` on each child model before assigning to `items`.

```
embedded_entities = []
children.each do |child|
  embedded_entities << child.build_entity
end
primary.items = embedded_entities
primary.save
```

**Comment by NielsKSchjoedt** [comment]
Thanks, very helpful. So, I'm a bit unsure of the whole use of `ancestors`/`children` VS embedded entities. Our use case is this:

Consider this simple example setup:

```ruby
class PrimaryModel
  include ActiveModel::Datastore

  ATTRIBUTES = %i{some_context other_context}
  attr_accessor *ATTRIBUTES

  def entity_properties
    ATTRIBUTES
  end
end

class ContextualFeatures
  include ActiveModel::Datastore

  ATTRIBUTES = %i{has_this has_that time_stamp some_description}
  attr_accessor *ATTRIBUTES

  def entity_properties
    ATTRIBUTES
  end
end
```

Now according to your description I can do something like this:

```ruby
mp = PrimaryModel.new(
  some_context: ContextualFeatures.new(
    has_this: true,
    has_that: false,
    time_stamp: Time.zone.now,
    some_description: 'Here is some random text'
  ).build_entity,
  other_context: ContextualFeatures.new(
    has_this: false,
    has_that: false,
    time_stamp: Time.zone.now,
    some_description: 'Super important message!'
  ).build_entity
)
mp.save
```

This works and creates the embedded entity. Now when I wanna retrieve the PrimaryEntity back like so: `mp = PrimaryEntity.find(1)` the value of `mp.some_context` or `mp.other_context` is an instance of `Google::Cloud::Datastore::Entity`. Is there any "standard"/"build-in"/"best way" of transforming that into an instance of `ContextualFeatures`? Or am I doing this all wrong, should do things differently?

Also, do I understand correctly that this way of doing things I am utilising the "embedded_entities" property functionality of Firestore rather than the `parent`/`child`-thingy, which comes with e.g. the write throughput limitation of 1 write per 1 sec?

Hope it's OK I ask. I would like to contribute with some README examples, but I need to make sure I understand things right first :-)

**Comment by bmclean** [comment]
Yes, your example is using embedded entities. With the parent/child relationship you have separate entities and you set the parent id in the key of the child entity.

For example, if you added this to your ContextualFeatures model:
```
def self.parent_key(id)
  CloudDatastore.dataset.key('PrimaryModel', id)
end
```
you could create them like this:
```
ContextualFeatures.new(
  has_this: false,
  has_that: false,
  time_stamp: Time.zone.now,
  some_description: 'Super important message!',
  parent_key_id: 1 # id of the parent
)
```
Your ContextualFeatures could then be queried using the parent_key. This is described in more detail in the README [here](https://github.com/Agrimatics/activemodel-datastore#datastore-consistency).

Which is better? That is completely dependent on your application.

**Comment by bmclean** [comment]
There is no "standard"/"build-in"/"best way" of transforming the embedded entities back into models. It always ends up being application specific. You can make use of the `from_entity` method though.
