### ISSUE TITLE
GAE Production authentication is overridden with emulator settings

### ISSUE THREAD

**Issue by rjmooney** [Agrimatics/activemodel-datastore#8]
GAE Production authentication appears to be overridden with hardcoded emulator settings. The initialization code in [lib/active_model/datastore/connection.rb](https://github.com/Agrimatics/activemodel-datastore/blob/72ca865d3ac69639a671e8f430d32ba4ad5567e6/lib/active_model/datastore/connection.rb) overrides the `GCLOUD_PROJECT` environment variable with the test datastore project and sets `DATASTORE_EMULATOR_HOST` regardless of the existing environment. The latter forces emulator usage.

```ruby
module CloudDatastore
  if defined?(Rails) == 'constant'
    if Rails.env.development?
      ENV['DATASTORE_EMULATOR_HOST'] = 'localhost:8180'
      ENV['GCLOUD_PROJECT'] = 'local-datastore'
    elsif Rails.env.test?
      ENV['DATASTORE_EMULATOR_HOST'] = 'localhost:8181'
      ENV['GCLOUD_PROJECT'] = 'test-datastore'
    elsif ENV['SERVICE_ACCOUNT_PRIVATE_KEY'].present? &&
          ENV['SERVICE_ACCOUNT_CLIENT_EMAIL'].present?
      ENV['GCLOUD_KEYFILE_JSON'] = '{"private_key": "' + ENV['SERVICE_ACCOUNT_PRIVATE_KEY'] + '",
      "client_email": "' + ENV['SERVICE_ACCOUNT_CLIENT_EMAIL'] + '"}'
    end
  else
    ENV['DATASTORE_EMULATOR_HOST'] = 'localhost:8181'
    ENV['GCLOUD_PROJECT'] = 'test-datastore'
  end

  def self.dataset
    @dataset ||= Google::Cloud.datastore(ENV['GCLOUD_PROJECT'])
  end
...
```

Maybe I'm missing something but it seems the model should _not_ override the environment and simply allow `Google::Cloud.datastore` to initialize using the existing environment per the [Google Cloud Client Library convention](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/AUTHENTICATION.md).

**Comment by bmclean** [comment]
Thanks for the issue @rjmooney! You are correct, this is a problem when used outside of Rails. The condition that your code would be using was actually put in for the gem test suite, which doesn't use Rails.

Regarding the use of environment variables, they are required when running anywhere outside of Google Compute Engine. The intent was that if `SERVICE_ACCOUNT_PRIVATE_KEY`, `SERVICE_ACCOUNT_CLIENT_EMAIL` and `GCLOUD_PROJECT` are not present in the Rails production environment, then the dataset is initialized as the gcloud docs describe. However, this doesn't work if this gem is used with other Ruby frameworks.
